# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Takis Kapasakalidis - Personal Site
email: pkapasakalidis@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Information about skills, experience, projects, and certifications
domain: takis-kapas.github.io
baseurl: /takis-kapas # the subpath of your site, e.g. /blog
url: https://takis-kapas.github.io # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: panagiotis-kapasakalidis-6b5b0322
github_username:  takis-kapas

urls:
    - text: Home
      url: /
    - text: Skills
      url: /skills
    - text: Experience
      url: /experience
    - text: Projects
      url: /projects
    - text: Certifications
      url : /certifications

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: author.png
author: Takis Kapasakalidis
author_bio: I am a DevOps Technical Architect with more than ten years of experience supporting Agile teams in the healthcare industry. <p>I work closely with business and technical leaders on identifying requirements to apply best practices for their software development lifecycle, though the implementation of appropriate methodologies and workflows for code management, build and release deployment, and IaC operations. <p>My specialization is on DevSecOps strategy and administration of complex environments and operations on Azure DevOps Services and GitHub Enterprise Cloud EMU platforms. 
author_email: "pkapasakalidis@gmail.com"
author_location: Wilmington, Massachusetts
author_website_url: ""
typewrite-text: Typewrite Test
hero_cover_img: Bentley_Logo.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# Experiences
author_work_experiences:
            - company_name: Mass General Brigham
              company_logo: mgb.jpeg
              company_url: https://www.massgeneralbrigham.org/
              designation: DevOps Technical Architect
              description: Leading strategic initiatives for the “Journey to Cloud” migration requirements on Azure DevOps Services and GitHub Enterprise Cloud
              long_description: architect.html
              visibility: true
            - company_name: Mass General Brigham
              company_logo: mgb.jpeg
              company_url: https://www.massgeneralbrigham.org/
              designation: Sr. Project Specialist
              description: Designed, published, and communicated TFS and Azure DevOps governance and policies around Project Management, Source Code Management, CI/CD deployment, and Test execution
              long_description: architect.html
              visibility: true

# Education
author_education_details:
              - college_logo: Bentley_Logo.png
                college_name: Bentley University
                college_url: https://www.bentley.edu/
                college_degree: MSIT
                description: Masters of Science in Information Technology
                visibility: true
              - college_logo: ACG_Logo.jpg
                college_name: American College of Greece (DEREE)
                college_url: https://www.acg.edu/
                college_degree: BS in MSIT
                description: Bachelor of Science in Information Technology
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# Build settings
theme: minima
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-figure
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
