# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Takis Kapasakalidis - Personal Site
email: pkapasakalidis@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Information about experience, projects, certifications
domain: takis-kapas.github.io
baseurl: /takis-kapas # the subpath of your site, e.g. /blog
url: https://takis-kapas.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pkapasakalidis
github_username:  takis-kapas

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Experience
      url: /blog
    - text: Projects
      url: /gallery
    - text: Contact
      url : /shop

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: John Doe
author_bio: Hi, my name is John Doe. I built this site using devlopr-jekyll :D
author_email: "mail@sujaykundu.com"
author_location: India
author_website_url: "https://sujaykundu.com"
typewrite-text: devlopr is a jekyll framework built for developers. You can edit this in _config.yml file
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: true

# Education
author_education_details:
              - college_logo: Bentley_logo.png
                college_name: Bentley University
                college_url: https://www.bentley.edu/
                college_degree: MSIT
                description: Masters of Science in Information Technology
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# Build settings
theme: minima
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
